#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
import math

from hri_engagement.engagement_node import MAX_DISTANCE, REFERENCE_FRAME, FOV, VISUAL_SOCIAL_ENGAGEMENT_THR, EngagementNode

if __name__ == "__main__":
    rospy.init_node("engagement_monitor")
    MAX_DISTANCE = rospy.get_param(
        "~max_distance", default=MAX_DISTANCE)
    REFERENCE_FRAME = rospy.get_param(
        "~reference_frame", default=REFERENCE_FRAME)
    FOV = rospy.get_param("~field_of_view", default=FOV *
                          180/math.pi) * math.pi / 180
    VISUAL_SOCIAL_ENGAGEMENT_THR = rospy.get_param(
        "~engagement_threshold", default=VISUAL_SOCIAL_ENGAGEMENT_THR
    )
    node = EngagementNode(VISUAL_SOCIAL_ENGAGEMENT_THR, REFERENCE_FRAME)
    node.run()
